### ISSUE TITLE
wc_webhooks' doesn't exist

### ISSUE THREAD

**Issue by Krammig** [awesomemotive/Transients-Manager#48]
It is showing some 345 pages of Transients although a couple of other apps are only showing 4 transients since the last clean I did a few minutes ago with another app. 

That is a huge discrepancy but I'm not saying it is wrong, it just seems very odd so flagging it here. 

Also, I thought I would run the Delete anyway (backup done) and I got the follwoing error immediately ; 

wc_webhooks' doesn't exist  

Any idea?

thanks

**Comment by pippinsplugins** [comment]
Can you show me the exact error message that was shown for `wc_webhooks`?

**Comment by JJJ** [comment]
`wc_webhooks` appears to be part of WooCommerce, as the name of a custom database table, in relation to a custom wrapper for using Transients to cache their Webhook requests.

WooCommerce uses Transients for a lot of things (orders, wizards, helpers, reports, statuses, geolocation, etc...) so, if I needed to guess, the database table probably went missing (or wasn't created) and the error message didn't appear until the relative Transients were flushed.

Gonna close this issue, since it's a few years old and likely unrelated to this plugin specifically.

Definitely reopen though if there is anymore info. 💕
